#!/bin/bash

. /etc/os-release
. /etc/armbian-release

KERNELID=$(uname -r)
TERM=linux toilet -f standard -F border hack0
echo -e "Welcome to $(echo $NAME | cut -d' ' -f1) $(if [[ $ID == debian ]]; then echo ${PRETTY_NAME##*\(} | rev | cut -c2- | rev | sed 's/.*/\u&/'; else echo -n ${VERSION_CODENAME^};fi) with \e[0;91mArmbian Linux\x1B[0m $KERNELID"